[package]
name = "timemark"
version = "0.1.0"
description = "TimeMark native package application"
authors = ["TimeMark"]
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "lib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
